# Generated by Django 3.2.9 on 2021-11-23 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='userid',
            new_name='username',
        ),
    ]
