# Generated by Django 3.2.9 on 2021-11-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_registration_name_brand_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quntity',
            field=models.IntegerField(),
        ),
    ]
