# Generated by Django 3.2.9 on 2021-11-26 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='category_name',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Product_Category',
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
